Repository open-rpc/logs-react, pull requests merged in 2020-05, with the labels that each got.

#11 Feat/chrome dev extension
  .env
  package-lock.json
  package.json
  public/index.css
  public/manifest.json
  src/components/Introspector.test.tsx
  src/components/Introspector.tsx
  src/containers/MyApp.tsx
  src/hooks/useWebRequest.ts
Labels: enhancement

#20 fix: keep useWebRequest history integrity
  package-lock.json
  src/components/cardList.tsx
  src/components/logs-react.tsx
  src/containers/MyApp.tsx
  src/hooks/useWebRequest.ts
Labels: bug

#21 Fix: Add Basic GUI and Chrome Extension
  package-lock.json
  package.json
  public/manifest.json
  src/components/cardList.tsx
  src/components/cardListItem.tsx
  src/components/logs-react.tsx
  src/containers/MyApp.tsx
  src/hooks/useWebRequest.ts
  tsconfig.json
Labels: bug, enhancement
