Repository open-rpc/logs-react, pull requests merged in 2020-06, with the labels that each got.

#32 Feat: Messenger like GUI and method filtering
  .editorconfig
  src/components/cardList.tsx
  src/components/cardList/cardList.tsx
  src/components/cardListItem.tsx
  src/components/cardListItem/cardListItem.css
  src/components/cardListItem/cardListItem.tsx
  src/components/logs-react.tsx
  src/components/logsReact/logsReact.css
  src/components/logsReact/logsReact.tsx
  src/components/methodList/methodList.css
  src/components/methodList/methodList.tsx
  src/components/methodListItem/methodListItem.css
  src/components/methodListItem/methodListItem.tsx
  src/containers/MyApp.css
  src/containers/MyApp.tsx
  src/exports.ts
  src/hooks/useWebRequest.ts
  src/themes/theme.ts
  tsfmt.json
  tslint.json
Labels: enhancement

#34 Fix: syntax highlighting and formatting update
  .editorconfig
  package-lock.json
  package.json
  rescript-monaco.js
  src/components/cardList/cardList.tsx
  src/components/cardListItem/cardListItem.css
  src/components/cardListItem/cardListItem.tsx
  src/components/logsReact/logsReact.css
  src/components/logsReact/logsReact.tsx
  src/components/methodList/methodList.css
  src/components/methodList/methodList.tsx
  src/components/methodListItem/methodListItem.css
  src/components/methodListItem/methodListItem.tsx
  src/containers/MyApp.css
  src/containers/MyApp.tsx
  src/hooks/useWebRequest.ts
  src/themes/theme.ts
  tsfmt.json
  tslint.json
Labels: bug

#38 Feature: Copy payload to clipboard
  package-lock.json
  package.json
  src/components/alert/alert.tsx
  src/components/cardListItem/cardListItem.tsx
  src/components/methodList/methodList.tsx
Labels: enhancement

#40 fix: add circleci context
  .circleci/config.yml
Labels: bug

#41 fix: add tslint fixes
  src/components/alert/alert.tsx
  src/components/cardList/cardList.tsx
  src/components/cardListItem/cardListItem.tsx
  src/components/logsReact/logsReact.tsx
  src/components/methodList/methodList.tsx
  src/containers/MyApp.tsx
Labels: bug

#42 fix: add npm release target
  .releaserc
Labels: bug

#43 fix: remove package folder
  .gitignore
  package/components/Introspector.d.ts
  package/components/Introspector.js
  package/containers/LanguageMenu/LanguageMenu.d.ts
  package/containers/LanguageMenu/LanguageMenu.js
  package/containers/LanguageMenu/index.d.ts
  package/containers/LanguageMenu/index.js
  package/containers/MyApp.d.ts
  package/containers/MyApp.js
  package/i18n.d.ts
  package/i18n.js
  package/index.d.ts
  package/index.js
  package/themes/theme.d.ts
  package/themes/theme.js
  package/translations/cn.d.ts
  package/translations/cn.js
  package/translations/en.d.ts
  package/translations/en.js
  package/translations/kr.d.ts
  package/translations/kr.js
Labels: bug

#45 fix: update dependencies to match inspector
  package-lock.json
  package.json
Labels: bug

#46 fix: copy css into package
  package-lock.json
  package.json
Labels: bug

#47 fix: export JSONRPCLog type
  README.md
  src/exports.ts
Labels: bug

#50 fix: change the sidebar to a material ui drawer
  src/components/logsReact/logsReact.css
  src/components/logsReact/logsReact.tsx
  src/components/methodList/methodList.css
  src/components/methodList/methodList.tsx
  src/components/methodListItem/methodListItem.css
  src/components/methodListItem/methodListItem.tsx
  src/containers/MyApp.tsx
  src/themes/theme.ts
Labels: bug, enhancement

#52 fix: remove appbar
  src/components/logsReact/logsReact.css
  src/components/logsReact/logsReact.tsx
  src/components/methodList/methodList.css
  src/components/methodList/methodList.tsx
Labels: bug

#53 fix: remove excessive card padding
  src/components/cardListItem/cardListItem.tsx
Labels: bug

#54 fix: slide animation is restricted to div
  src/components/methodList/methodList.tsx
Labels: bug
